# 这些是控制哪些赞助按钮出现在您的仓库页面的设置。

# GitHub 赞助组织文件
github: [yourusername]

# 这些是开发者用来资助您的工作的赞助平台。
# 填写您使用的平台并删除您不使用的平台。
# 要禁用所有赞助，可以将此文件留空或运行 `gh repo edit --disable-sponsorship`

# Patreon 用户名
patreon: yourusername

# Open Collective 用户名
open_collective: telegram-mcp-complete

# Ko-fi 用户名
ko_fi: yourusername

#_tid_labs 用户名
tidelabs: yourusername

# Community Bridge 项目名称 e.g., `cloud-foundry`
community_bridge: telegram-mcp-complete

# Liberapay 用户名
liberapay: yourusername

# Issuehunt 用户名
issuehunt: yourusername

# Otechie 用户名
otechie: yourusername

# LFX Crowdfunding 用户名 e.g., `cloud-foundry`
lfx_crowdfunding: telegram-mcp-complete

# Polar 用户名
polar: yourusername

# Buy Me a Coffee 用户名
buy_me_a_coffee: yourusername

# Custom 赞助 URL
custom: ['https://paypal.me/yourusername']
